# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

build_tree_network_cpp <- function(var_conc, var_tip_id, nodeSZ, dpthST, is_leaf) {
    .Call(`_multiRF_build_tree_network_cpp`, var_conc, var_tip_id, nodeSZ, dpthST, is_leaf)
}

compute_split_stats_cpp <- function(Y, membership, mem_left, mem_right) {
    .Call(`_multiRF_compute_split_stats_cpp`, Y, membership, mem_left, mem_right)
}

tsne_cost_gradient_cpp <- function(Y, P) {
    .Call(`_multiRF_tsne_cost_gradient_cpp`, Y, P)
}

